### ISSUE TITLE
postpage image in assets folder is corrupt

### ISSUE THREAD

**Issue by DaveSaah** [boring-school-work/cookitup#22]
@Olivianm  and @emmanuel-b-agyei the postimage placed in the assets folder is corrupted, kindly replace it.

**Comment by emmanuel-b-agyei** [comment]
through a new branch or the register-page branch will work?

**Comment by DaveSaah** [comment]
Kindly create a new branch and make the necessary changes.

Give on git branches: https://www.youtube.com/watch?v=e2IbNHi4uCI&pp=ygUMZ2l0IGJyYW5jaGVz
